#!/bin/bash
#
# generate-report.sh - Generate test reports
# Usage: ./generate-report.sh [options]
# Options:
#   --format <type>  Report format (html|json|markdown)
#   --input <file>   Input JSON file
#   --history        Include historical data
#   --output <file>  Output file
#   --quiet          Minimal output
#

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SKILL_DIR="$(dirname "$SCRIPT_DIR")"
DATA_DIR="$SKILL_DIR/data"
RESULTS_DIR="$DATA_DIR/test-results"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m'

# Options
FORMAT="markdown"
INPUT_FILE="$RESULTS_DIR/latest.json"
INCLUDE_HISTORY=0
OUTPUT_FILE=""
QUIET=0

# Parse arguments
while [[ $# -gt 0 ]]; do
  case $1 in
    --format) FORMAT="$2"; shift 2 ;;
    --input) INPUT_FILE="$2"; shift 2 ;;
    --history) INCLUDE_HISTORY=1; shift ;;
    --output) OUTPUT_FILE="$2"; shift 2 ;;
    --quiet) QUIET=1; shift ;;
    *) echo "Unknown option: $1"; exit 2 ;;
  esac
done

log() {
  if [[ $QUIET -eq 0 ]]; then
    echo -e "$@"
  fi
}

# Check if input file exists
if [[ ! -f "$INPUT_FILE" ]]; then
  echo "Error: Input file not found: $INPUT_FILE"
  exit 1
fi

# Parse JSON data
TIMESTAMP=$(cat "$INPUT_FILE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('timestamp', 'unknown'))" 2>/dev/null || echo "unknown")
DATE=$(cat "$INPUT_FILE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('date', 'unknown'))" 2>/dev/null || echo "unknown")
TOTAL=$(cat "$INPUT_FILE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('summary', {}).get('total', 0))" 2>/dev/null || echo "0")
PASSED=$(cat "$INPUT_FILE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('summary', {}).get('passed', 0))" 2>/dev/null || echo "0")
FAILED=$(cat "$INPUT_FILE" | python3 -c "import json,sys; print(json.load(sys.stdin).get('summary', {}).get('failed', 0))" 2>/dev/null || echo "0")

# Calculate percentage
if [[ $TOTAL -gt 0 ]]; then
  PERCENTAGE=$((PASSED * 100 / TOTAL))
else
  PERCENTAGE=0
fi

# Generate Markdown report
generate_markdown() {
  local output="$1"
  
  cat > "$output" << EOF
# OpenClaw Tool Tester Report

**Generated:** $DATE  
**Timestamp:** $TIMESTAMP

## Summary

| Metric | Value |
|--------|-------|
| Total Tests | $TOTAL |
| Passed | $PASSED ✅ |
| Failed | $FAILED ❌ |
| Success Rate | $PERCENTAGE% |

## Results by Category

EOF

  # Add detailed results
  python3 << PYEOF
import json

with open('$INPUT_FILE') as f:
    data = json.load(f)

results = data.get('results', {})

for name, result in sorted(results.items()):
    status = result.get('status', 'UNKNOWN')
    duration = result.get('duration', 0)
    icon = '✅' if status == 'PASS' else '❌'
    print(f"### {icon} {name}")
    print(f"- **Status:** {status}")
    print(f"- **Duration:** {duration}s")
    print()
PYEOF

  cat >> "$output" << EOF

## Recommendations

EOF

  if [[ $FAILED -eq 0 ]]; then
    echo "All tests passed! No action required." >> "$output"
  else
    echo "⚠️ Some tests failed. Review the detailed results above and:" >> "$output"
    echo "" >> "$output"
    echo "1. Check tool configurations" >> "$output"
    echo "2. Verify API keys are set" >> "$output"
    echo "3. Ensure required services are running" >> "$output"
    echo "4. Review network connectivity" >> "$output"
  fi

  cat >> "$output" << EOF

---

*Generated by tool-tester skill*
EOF
}

# Generate HTML report
generate_html() {
  local output="$1"
  local status_color="#28a745"
  
  if [[ $FAILED -gt 0 ]]; then
    status_color="#dc3545"
  fi
  
  cat > "$output" << EOF
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Tool Tester Report</title>
    <style>
        body { font-family: -apple-system, BlinkMacSystemFont, sans-serif; max-width: 900px; margin: 40px auto; padding: 20px; }
        h1 { color: #333; }
        .summary { background: #f8f9fa; padding: 20px; border-radius: 8px; margin: 20px 0; }
        .metric { display: inline-block; margin: 10px 20px; }
        .metric-value { font-size: 32px; font-weight: bold; color: $status_color; }
        .metric-label { color: #666; }
        .pass { color: #28a745; }
        .fail { color: #dc3545; }
        table { width: 100%; border-collapse: collapse; margin: 20px 0; }
        th, td { padding: 12px; text-align: left; border-bottom: 1px solid #ddd; }
        th { background: #f8f9fa; }
        tr:hover { background: #f8f9fa; }
    </style>
</head>
<body>
    <h1>🔧 OpenClaw Tool Tester Report</h1>
    <p>Generated: <strong>$DATE</strong></p>
    
    <div class="summary">
        <h2>Summary</h2>
        <div class="metric">
            <div class="metric-value">$TOTAL</div>
            <div class="metric-label">Total Tests</div>
        </div>
        <div class="metric">
            <div class="metric-value" style="color: #28a745;">$PASSED</div>
            <div class="metric-label">Passed</div>
        </div>
        <div class="metric">
            <div class="metric-value" style="color: #dc3545;">$FAILED</div>
            <div class="metric-label">Failed</div>
        </div>
        <div class="metric">
            <div class="metric-value">$PERCENTAGE%</div>
            <div class="metric-label">Success Rate</div>
        </div>
    </div>
    
    <h2>Results by Category</h2>
    <table>
        <tr>
            <th>Test</th>
            <th>Status</th>
            <th>Duration</th>
        </tr>
EOF

  python3 << PYEOF >> "$output"
import json

with open('$INPUT_FILE') as f:
    data = json.load(f)

results = data.get('results', {})

for name, result in sorted(results.items()):
    status = result.get('status', 'UNKNOWN')
    duration = result.get('duration', 0)
    css_class = 'pass' if status == 'PASS' else 'fail'
    print(f"<tr><td>{name}</td><td class='{css_class}'>{status}</td><td>{duration}s</td></tr>")
PYEOF

  cat >> "$output" << EOF
    </table>
    
    <footer>
        <p><small>Generated by tool-tester skill</small></p>
    </footer>
</body>
</html>
EOF
}

# Generate JSON report (formatted)
generate_json() {
  local output="$1"
  python3 -m json.tool "$INPUT_FILE" > "$output"
}

# Main execution
log "${BLUE}Generating Test Report...${NC}"

# Determine output file
if [[ -z "$OUTPUT_FILE" ]]; then
  case "$FORMAT" in
    html) OUTPUT_FILE="$RESULTS_DIR/report-$TIMESTAMP.html" ;;
    json) OUTPUT_FILE="$RESULTS_DIR/report-$TIMESTAMP.json" ;;
    markdown) OUTPUT_FILE="$RESULTS_DIR/report-$TIMESTAMP.md" ;;
    *) echo "Unknown format: $FORMAT"; exit 2 ;;
  esac
fi

# Generate report
mkdir -p "$(dirname "$OUTPUT_FILE")"

case "$FORMAT" in
  html)
    generate_html "$OUTPUT_FILE"
    ;;
  json)
    generate_json "$OUTPUT_FILE"
    ;;
  markdown)
    generate_markdown "$OUTPUT_FILE"
    ;;
esac

log "${GREEN}✓ Report generated:${NC} $OUTPUT_FILE"

# Display summary
log ""
log "Summary: ${GREEN}$PASSED passed${NC}, ${RED}$FAILED failed${NC} (${PERCENTAGE}% success rate)"
